// This file is generated by Slice Machine. Update with care!

import ChartRow from './ChartRow';
import LearnAndEarnCategory from './LearnAndEarnCategory';
import LearnAndEarnQuestion from './LearnAndEarnQuestion';
import LearnAndEarnTutorialSlide from './LearnAndEarnTutorialSlide';
import SideMenuItem from './SideMenuItem';

export {
	ChartRow,
	LearnAndEarnCategory,
	LearnAndEarnQuestion,
	LearnAndEarnTutorialSlide,
	SideMenuItem,
};

export const components = {
	chart_row: ChartRow,
	learn_and_earn_category: LearnAndEarnCategory,
	learn_and_earn_question: LearnAndEarnQuestion,
	learn_and_earn_tutorial_slide: LearnAndEarnTutorialSlide,
	side_menu_item: SideMenuItem,
};
