// This file is generated by Slice Machine. Update with care!

import ChartRow from './ChartRow';
import SideMenuItem from './SideMenuItem';

export {
	ChartRow,
	SideMenuItem,
};

export const components = {
	chart_row: ChartRow,
	side_menu_item: SideMenuItem,
};
